// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/datamsg.proto

package datamsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LevelType int32

const (
	LevelType_SECONDARY1 LevelType = 0
	LevelType_SECONDARY2 LevelType = 1
	LevelType_SECONDARY3 LevelType = 2
	LevelType_SECONDARY4 LevelType = 3
)

// Enum value maps for LevelType.
var (
	LevelType_name = map[int32]string{
		0: "SECONDARY1",
		1: "SECONDARY2",
		2: "SECONDARY3",
		3: "SECONDARY4",
	}
	LevelType_value = map[string]int32{
		"SECONDARY1": 0,
		"SECONDARY2": 1,
		"SECONDARY3": 2,
		"SECONDARY4": 3,
	}
)

func (x LevelType) Enum() *LevelType {
	p := new(LevelType)
	*p = x
	return p
}

func (x LevelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LevelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datamsg_proto_enumTypes[0].Descriptor()
}

func (LevelType) Type() protoreflect.EnumType {
	return &file_proto_datamsg_proto_enumTypes[0]
}

func (x LevelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LevelType.Descriptor instead.
func (LevelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{0}
}

type StreamType int32

const (
	StreamType_EXPRESS         StreamType = 0
	StreamType_NORMALACADEMIC  StreamType = 2
	StreamType_NORMALTECHNICAL StreamType = 3
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "EXPRESS",
		2: "NORMALACADEMIC",
		3: "NORMALTECHNICAL",
	}
	StreamType_value = map[string]int32{
		"EXPRESS":         0,
		"NORMALACADEMIC":  2,
		"NORMALTECHNICAL": 3,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datamsg_proto_enumTypes[1].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_proto_datamsg_proto_enumTypes[1]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{1}
}

type TransactionCode int32

const (
	TransactionCode_TRANSACTIONSUCCESS TransactionCode = 0
	TransactionCode_TRANSACTIONFAIL    TransactionCode = 1
)

// Enum value maps for TransactionCode.
var (
	TransactionCode_name = map[int32]string{
		0: "TRANSACTIONSUCCESS",
		1: "TRANSACTIONFAIL",
	}
	TransactionCode_value = map[string]int32{
		"TRANSACTIONSUCCESS": 0,
		"TRANSACTIONFAIL":    1,
	}
)

func (x TransactionCode) Enum() *TransactionCode {
	p := new(TransactionCode)
	*p = x
	return p
}

func (x TransactionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_datamsg_proto_enumTypes[2].Descriptor()
}

func (TransactionCode) Type() protoreflect.EnumType {
	return &file_proto_datamsg_proto_enumTypes[2]
}

func (x TransactionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionCode.Descriptor instead.
func (TransactionCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{2}
}

type Books struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subject string     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Price   float64    `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stream  StreamType `protobuf:"varint,4,opt,name=stream,proto3,enum=datamsg.StreamType" json:"stream,omitempty"`
	Level   LevelType  `protobuf:"varint,5,opt,name=level,proto3,enum=datamsg.LevelType" json:"level,omitempty"`
}

func (x *Books) Reset() {
	*x = Books{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datamsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Books) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Books) ProtoMessage() {}

func (x *Books) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Books.ProtoReflect.Descriptor instead.
func (*Books) Descriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{0}
}

func (x *Books) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Books) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Books) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Books) GetStream() StreamType {
	if x != nil {
		return x.Stream
	}
	return StreamType_EXPRESS
}

func (x *Books) GetLevel() LevelType {
	if x != nil {
		return x.Level
	}
	return LevelType_SECONDARY1
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Phone   int32  `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datamsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Person) GetPhone() int32 {
	if x != nil {
		return x.Phone
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	Customer        *Person                `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Bookslist       []*Books               `protobuf:"bytes,4,rep,name=bookslist,proto3" json:"bookslist,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datamsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *Transaction) GetCustomer() *Person {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Transaction) GetBookslist() []*Books {
	if x != nil {
		return x.Bookslist
	}
	return nil
}

type BookQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qlevel  LevelType  `protobuf:"varint,1,opt,name=qlevel,proto3,enum=datamsg.LevelType" json:"qlevel,omitempty"`
	Qstream StreamType `protobuf:"varint,2,opt,name=qstream,proto3,enum=datamsg.StreamType" json:"qstream,omitempty"`
}

func (x *BookQuery) Reset() {
	*x = BookQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datamsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookQuery) ProtoMessage() {}

func (x *BookQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookQuery.ProtoReflect.Descriptor instead.
func (*BookQuery) Descriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{3}
}

func (x *BookQuery) GetQlevel() LevelType {
	if x != nil {
		return x.Qlevel
	}
	return LevelType_SECONDARY1
}

func (x *BookQuery) GetQstream() StreamType {
	if x != nil {
		return x.Qstream
	}
	return StreamType_EXPRESS
}

type TransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code TransactionCode `protobuf:"varint,1,opt,name=code,proto3,enum=datamsg.TransactionCode" json:"code,omitempty"`
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_datamsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datamsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_proto_datamsg_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionReply) GetCode() TransactionCode {
	if x != nil {
		return x.Code
	}
	return TransactionCode_TRANSACTIONSUCCESS
}

var File_proto_datamsg_proto protoreflect.FileDescriptor

var file_proto_datamsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa4, 0x01, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x2b, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x28, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x4c, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x10, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12,
	0x2c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x66, 0x0a,
	0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x71, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6d, 0x73, 0x67, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x71, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x07, 0x71, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73,
	0x67, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x71, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x40, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73,
	0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x4b, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52,
	0x59, 0x31, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52,
	0x59, 0x32, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52,
	0x59, 0x33, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52,
	0x59, 0x34, 0x10, 0x03, 0x2a, 0x42, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x52, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x41, 0x43, 0x41, 0x44, 0x45, 0x4d, 0x49,
	0x43, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x54, 0x45, 0x43,
	0x48, 0x4e, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x03, 0x2a, 0x3e, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x32, 0x57, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0x3e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x12, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x1a, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x6b, 0x70, 0x65, 0x68, 0x2f, 0x77, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_datamsg_proto_rawDescOnce sync.Once
	file_proto_datamsg_proto_rawDescData = file_proto_datamsg_proto_rawDesc
)

func file_proto_datamsg_proto_rawDescGZIP() []byte {
	file_proto_datamsg_proto_rawDescOnce.Do(func() {
		file_proto_datamsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_datamsg_proto_rawDescData)
	})
	return file_proto_datamsg_proto_rawDescData
}

var file_proto_datamsg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_datamsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_datamsg_proto_goTypes = []interface{}{
	(LevelType)(0),                // 0: datamsg.LevelType
	(StreamType)(0),               // 1: datamsg.StreamType
	(TransactionCode)(0),          // 2: datamsg.TransactionCode
	(*Books)(nil),                 // 3: datamsg.Books
	(*Person)(nil),                // 4: datamsg.Person
	(*Transaction)(nil),           // 5: datamsg.Transaction
	(*BookQuery)(nil),             // 6: datamsg.BookQuery
	(*TransactionReply)(nil),      // 7: datamsg.TransactionReply
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_datamsg_proto_depIdxs = []int32{
	1,  // 0: datamsg.Books.stream:type_name -> datamsg.StreamType
	0,  // 1: datamsg.Books.level:type_name -> datamsg.LevelType
	8,  // 2: datamsg.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	4,  // 3: datamsg.Transaction.customer:type_name -> datamsg.Person
	3,  // 4: datamsg.Transaction.bookslist:type_name -> datamsg.Books
	0,  // 5: datamsg.BookQuery.qlevel:type_name -> datamsg.LevelType
	1,  // 6: datamsg.BookQuery.qstream:type_name -> datamsg.StreamType
	2,  // 7: datamsg.TransactionReply.code:type_name -> datamsg.TransactionCode
	5,  // 8: datamsg.SetTransactionInfo.SetTransaction:input_type -> datamsg.Transaction
	6,  // 9: datamsg.GetBooksInfo.GetBooks:input_type -> datamsg.BookQuery
	7,  // 10: datamsg.SetTransactionInfo.SetTransaction:output_type -> datamsg.TransactionReply
	3,  // 11: datamsg.GetBooksInfo.GetBooks:output_type -> datamsg.Books
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_datamsg_proto_init() }
func file_proto_datamsg_proto_init() {
	if File_proto_datamsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_datamsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Books); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datamsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datamsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datamsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_datamsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_datamsg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_datamsg_proto_goTypes,
		DependencyIndexes: file_proto_datamsg_proto_depIdxs,
		EnumInfos:         file_proto_datamsg_proto_enumTypes,
		MessageInfos:      file_proto_datamsg_proto_msgTypes,
	}.Build()
	File_proto_datamsg_proto = out.File
	file_proto_datamsg_proto_rawDesc = nil
	file_proto_datamsg_proto_goTypes = nil
	file_proto_datamsg_proto_depIdxs = nil
}
